# Generated by Django 3.1.5 on 2021-03-26 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iterwrite', '0004_auto_20210326_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(blank='True', default=None, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
