# Generated by Django 3.1.5 on 2021-03-26 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iterwrite', '0005_auto_20210326_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(default=None, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
