# Generated by Django 3.1.5 on 2021-03-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iterwrite', '0006_auto_20210326_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='about',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='influences',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='what',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='why',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
