# Generated by Django 3.1.5 on 2021-03-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iterwrite', '0007_auto_20210327_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='selection',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
